config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, controllers: {
    sessions: 'admin_user/sessions',
    registrations: 'admin_user/registrations',
    passwords: 'admin_user/passwords'
  }
  
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  root 'welcome#index'
  #resources :students

  namespace :admin do
    resources :students
    resources :projects
    resources :blogs
    resources :courses
    get 'dashboard' => 'dashboards#index'
  end

end

app/views/studentss/edit.html.erb
<div class="col-lg-8">

    <%= render "students/partials/flash_messages" %>
    <h1>Edit Student</h1>

    <%= render "students/partials/form", student: @student %>

</div>

app/views/studentss/index.html.erb
<div class="col-lg-10">
    <%= render "students/partials/flash_messages" %>

    <h1>Listing Students</h1>
    <div class="form-group" style="margin-bottom: 70px;"><%= link_to 'New Student', new_student_path, class: "btn btn-primary btn-lg", style: "float: right;" %></div>
    <table class="table table-bordered table-hover">
        <thead class="thead-dark">
            <tr>
                <th>Student</th> 
                <th colspan="3">Actions</th>
            </tr>
        </thead>
        <tbody class="tbody-light">
            <% @students.each do |student| %>
                <tr>
                    <td><%= student.name_with_email %></td>
                    <td><%= link_to "View", student %></td>
                    <td><%= link_to "Edit", edit_student_path(student) %></td>
                    <td><%= link_to 'Delete',student_path(student),data: {turbo_method: :delete, turbo_confirm: 'Are you sure?'}%></td>
                </tr>
            <% end %>
        </tbody>
</table>
</div>

app/views/studentss/new.html.erb
<div class="col-lg-8">

    <%= render "students/partials/flash_messages" %>
    
    <h1>New Student</h1>
    
    <%= render "students/partials/form", student: @student %>

</div>

app/views/studentss/show.html.erb
<div class="col-lg-10">
    <div class="card rounded-0 shadow mt-5 mb-5">
        <div class="card-body">
            <%= render "students/partials/flash_messages" %>
            
            <h1>Student Detail</h1>
            <p><strong>Name: </strong><%= @student.full_name %></p>
            <p><strong>E-mail: </strong><%= @student.email %></p>
            <p><strong>Date of Birth: </strong><%= formatted_date(@student.date_of_birth) %></p>
            <p><strong>Age: </strong><%= @student.age %></p>
            <p><strong>Permanent Address: </strong><%= @student.permanent_address %></p>
            <p><strong>Local Address: </strong><%= @student.local_address %></p>
            <p><strong>Permanent Contact: </strong><%= @student.permanent_contact_number %></p>
            <p><strong>Alternate Contact: </strong><%= @student.alternate_contact_number %></p>
        
            <%= link_to 'Back', students_path, class: "btn btn-danger btn-lg" %> | <%= link_to 'Edit', edit_student_path(@student), class: "btn btn-warning btn-lg" %>
        </div>
    </div>


</div>