config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, controllers: {
    sessions: 'admin_user/sessions',
    registrations: 'admin_user/registrations',
    passwords: 'admin_user/passwords'
  }
  
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  root 'welcome#index'
  #resources :students

  namespace :admin do
    resources :students
    resources :projects
    resources :blogs
    resources :courses
    get 'dashboard' => 'dashboards#index'
  end

end

app/models/student.rb
class Student < ApplicationRecord
  has_one_attached :profile_image

  has_many :blogs
  has_and_belongs_to_many :courses
  has_many :student_projects
  has_many :projects, through: :student_projects 

  validates :first_name, :last_name, :email, presence: true
  validates :email, uniqueness: :true
  validates :email, format: { with: /\A[^@\s]+@[^@\s]+\z/, message: "Geçersiz e-posta formatı" }
  validates :first_name, :last_name, length: {minimum:2, maximum:20}
  #validates :first_name, :last_name, format: { with: /\A[a-zA-Z]+\z/, message: "Sadece harf karakterleri kullanılabilir."}
  
  validate :validate_student_age

  after_create :display_student_age
  def display_student_age
    if self.date_of_birth.present?
      age = Date.today.year - self.date_of_birth.year
      puts "========= Age of student is #{age} =============="
    else
      puts "Age can not be calculated without date_of_birth"
    end
  end

  def validate_student_age
    if self.date_of_birth.present?
      age = Date.today.year - self.date_of_birth.year
      if age < 15
        errors.add(:age, "Please provide a valid date of birth here. Age must to be greather than 15.")
      end
    end
  end

  def full_name
    "#{first_name} #{last_name}"
  end

  def age
    return nil unless date_of_birth.present?
    return Date.today.year - date_of_birth.year
  end

  def name_with_email
    "#{full_name} / #{email}"
  end

  def self.ransackable_attributes(auth_object = nil)
    ["address", "email", "first_name", "last_name", "date_of_birth", "contact"]
  end
end

app/controllers/admin/students_controller.rb
class Admin::StudentsController < AdminController

  before_action :set_student, only: [:edit, :update, :show, :destroy]

  helper_method :formatted_date
  
  def index
    @q = Student.ransack(params[:q])
    @pagy, @students = pagy(@q.result(distinct: true))
  end

  def new
    @student = Student.new
  end

  def create
    @student = Student.new(student_params)
    if @student.save
      CrudNotificationMailer.create_notification(@student).deliver_now
      flash[:success] = "Student successfully created"
      redirect_to admin_students_path
    else
      flash[:error] = "Something went wrong"
      render 'new'
    end
  end

  def show
  end
  
  def edit
  end

  def update
      if @student.update(student_params)
        CrudNotificationMailer.update_notification(@student).deliver_now
        flash[:success] = "Student was successfully updated"
        redirect_to admin_student_path(@student)
      else
        flash[:error] = "Something went wrong"
        render 'edit'
      end
  end

  def destroy  
    @student.destroy
    CrudNotificationMailer.delete_notification(@student).deliver_now
      flash[:success] = 'Student was successfully deleted.'
      redirect_to admin_students_path
  end
  
  
  

  private 
  def student_params
    params.require(:student).permit(:first_name, :last_name, :email, :date_of_birth, :contact, :address, :permanent_contact_number, :local_address, :permanent_address, :alternate_contact_number, :profile_image)
  end

  def set_student
    @student = Student.find(params[:id])
  end

  def formatted_date date
    date.strftime('%A, %b %d %Y') if date.present?
  end


end

app/controllers/students_controller.rb
class StudentsController < ApplicationController
  layout 'admin'
  before_action :set_student, only: [:edit, :update, :show, :destroy]

  helper_method :formatted_date
  
  def index
    @students = Student.all.order(first_name: :desc)
  end

  def new
    @student = Student.new
  end

  def create
    @student = Student.new(student_params)
    if @student.save
      flash[:success] = "Student successfully created"
      redirect_to students_path
    else
      flash[:error] = "Something went wrong"
      render 'new'
    end
  end

  def show
  end
  
  def edit
  end

  def update
      if @student.update(student_params)
        flash[:success] = "Student was successfully updated"
        redirect_to student_path(@student)
      else
        flash[:error] = "Something went wrong"
        render 'edit'
      end
  end

  def destroy  
    @student.destroy
      flash[:success] = 'Student was successfully deleted.'
      redirect_to students_path
  end
  
  
  

  private 
  def student_params
    params.require(:student).permit(:first_name, :last_name, :email, :date_of_birth, :contact, :address)
  end

  def set_student
    @student = Student.find(params[:id])
  end

  def formatted_date date
    date.strftime('%A, %b %d %Y') if date.present?
  end

end

app/helpers/admin/students_helper.rb
module Admin::StudentsHelper
end

app/helpers/student_helper.rb
module StudentHelper
end

app/views/admin/students/edit.html.erb
<div class="col-lg-12">

    <%= render "admin/students/partials/flash_messages" %>
    <h1>Edit Student</h1>

    <%= render "admin/students/partials/form", student: @student %>

</div>

app/views/admin/students/index.html.erb
    <div class="col-lg-12">
        <%= render "admin/students/partials/flash_messages" %>
        <div class="form-group" style="display: flex; align-items: center;">
            <h1>Listing Students</h1>
        </div>
        <hr>
        <div class="form-group" style="margin-bottom: 100px;">
            <div style = "float: left;"><h1>Stundents: <%= @students.count %> / <%= Student.count %> </h1></div>
            <%= link_to 'New Student', new_admin_student_path, class: "btn btn-primary btn-lg", style: "float: right;" %>
        </div>

        <div class="row">
            <div class="col-2">
              <%= render 'shared/filters' %>
            </div>
            <div class="col-10">
            <table class="table table-bordered table-hover">
                <thead class="thead-dark">
                    <tr>
                        <th class="text-center"><%= sort_link(@q, :first_name, default_order: :asc) %></th>
                        <th class="text-center"><%= sort_link(@q, :last_name, default_order: :asc) %></th>
                        <th class="text-center"><%= sort_link(@q, :email, default_order: :asc) %></th> 
                        <th colspan="3" class="text-center">Actions</th>
                    </tr>
                </thead>
                <tbody class="tbody-light">
                    <% @students.each do |student| %>
                        <tr>
                            <td><%= student.first_name %></td>
                            <td><%= student.last_name %></td>
                            <td><%= student.email %></td>
                            <td class="text-center"><%= link_to "View", admin_student_path(student), class: "btn btn-primary btn-sm" %></td>
                            <td class="text-center"><%= link_to "Edit", edit_admin_student_path(student), class: "btn btn-warning btn-sm" %></td>
                            <td class="text-center"><%= link_to 'Delete',admin_student_path(student), data: {turbo_method: :delete, turbo_confirm: 'Are you sure?'}, class: "btn btn-danger btn-sm" %></td>
                        </tr>
                    <% end %>
                </tbody>
            </table>
            </div>
        </div>
        <div style="margin: 0 auto; width: 18%;"><%== pagy_bootstrap_nav(@pagy) %></div>

    </div>

app/views/admin/students/new.html.erb
<div class="col-lg-12">

    <%= render "admin/students/partials/flash_messages" %>
    
    <h1>New Student</h1>
    
    <%= render "admin/students/partials/form", student: @student %>

</div>

app/views/admin/students/show.html.erb
<div class="col-lg-12">
    <div class="card rounded-0 shadow mt-5 mb-5">
        <div class="card-body">
            <% if @student.profile_image.attached? %>
                <%= image_tag @student.profile_image, style: "width: 200px; heigh: 300px;" %>
            <% end %>
            <%= render "admin/students/partials/flash_messages" %>
            
            <h1>Student Detail</h1>
            <p><strong>Name: </strong><%= @student.full_name %></p>
            <p><strong>E-mail: </strong><%= @student.email %></p>
            <p><strong>Date of Birth: </strong><%= formatted_date(@student.date_of_birth) %></p>
            <p><strong>Age: </strong><%= @student.age %></p>
            <p><strong>Permanent Address: </strong><%= @student.permanent_address %></p>
            <p><strong>Local Address: </strong><%= @student.local_address %></p>
            <p><strong>Permanent Contact: </strong><%= @student.permanent_contact_number %></p>
            <p><strong>Alternate Contact: </strong><%= @student.alternate_contact_number %></p>
        
            <%= link_to 'Back', admin_students_path, class: "btn btn-danger btn-lg" %> | <%= link_to 'Edit', edit_admin_student_path(@student), class: "btn btn-warning btn-lg" %>
        </div>
    </div>


</div>