config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, controllers: {
    sessions: 'admin_user/sessions',
    registrations: 'admin_user/registrations',
    passwords: 'admin_user/passwords'
  }
  
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  root 'welcome#index'
  #resources :students

  namespace :admin do
    resources :students
    resources :projects
    resources :blogs
    resources :courses
    get 'dashboard' => 'dashboards#index'
  end

end

app/models/project.rb
class Project < ApplicationRecord
  include Validatable 

  has_many :student_projects
  has_many :students, through: :student_projects

  def self.ransackable_attributes(auth_object = nil)
    ["created_at", "description", "id", "name", "updated_at"]
  end

end

app/controllers/admin/projects_controller.rb
class Admin::ProjectsController < AdminController
  before_action :set_project, only: %i[ show edit update destroy ]

  # GET /projects or /projects.json
  def index
    @q = Project.ransack(params[:q])
    @pagy, @projects = pagy(@q.result(distinct: true))
  end

  # GET /projects/1 or /projects/1.json
  def show
  end

  # GET /projects/new
  def new
    @project = Project.new
  end

  # GET /projects/1/edit
  def edit
  end

  # POST /projects or /projects.json
  def create
    @project = Project.new(project_params)

    respond_to do |format|
      if @project.save
        format.html { redirect_to admin_project_url(@project), notice: "Project was successfully created." }
        format.json { render :show, status: :created, location: @project }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /projects/1 or /projects/1.json
  def update
    respond_to do |format|
      if @project.update(project_params)
        format.html { redirect_to admin_project_url(@project), notice: "Project was successfully updated." }
        format.json { render :show, status: :ok, location: @project }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /projects/1 or /projects/1.json
  def destroy
    @project.destroy

    respond_to do |format|
      format.html { redirect_to projects_url, notice: "Project was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_project
      @project = Project.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def project_params
      params.require(:project).permit(:name, :description)
    end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :set_project, only: %i[ show edit update destroy ]

  # GET /projects or /projects.json
  def index
    @projects = Project.all
  end

  # GET /projects/1 or /projects/1.json
  def show
  end

  # GET /projects/new
  def new
    @project = Project.new
  end

  # GET /projects/1/edit
  def edit
  end

  # POST /projects or /projects.json
  def create
    @project = Project.new(project_params)

    respond_to do |format|
      if @project.save
        format.html { redirect_to project_url(@project), notice: "Project was successfully created." }
        format.json { render :show, status: :created, location: @project }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /projects/1 or /projects/1.json
  def update
    respond_to do |format|
      if @project.update(project_params)
        format.html { redirect_to project_url(@project), notice: "Project was successfully updated." }
        format.json { render :show, status: :ok, location: @project }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /projects/1 or /projects/1.json
  def destroy
    @project.destroy

    respond_to do |format|
      format.html { redirect_to projects_url, notice: "Project was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_project
      @project = Project.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def project_params
      params.require(:project).permit(:name, :description)
    end
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/admin/projects/_filter.html.erb
<div class="card">
    <div class="card-header">
      Filters
    </div>
    <div class="card-body">
      <%= search_form_for @q, url: :admin_projects do |f| %>
        
        <div class="form-group">
          <%= f.label :name %>
          <%= f.text_field :name_start, class: 'form-control' %>
        </div>

        <div class="form-group">
          <%= f.label :description %>
          <%= f.text_field :description_cont, class: 'form-control' %>
        </div>      
      
        <div class="form-group">
          <%= f.label :created_at %>
          <%= f.date_field :created_at, class: 'form-control' %>
          <%= f.date_field :created_at, class: 'form-control' %>
        </div>
        
        <div class="form-group">
          <%= f.label :updated_at %>
          <%= f.date_field :updated_at_gteq, class: 'form-control' %>
          <%= f.date_field :updated_at_lteq, class: 'form-control' %>
        </div>

        <div class="form-group">
          <div class="float-right">
            <%= link_to "Clear", request.path, :class => "btn btn-default" %>
  
            <%= f.submit class: 'btn btn-primary' %>
          </div>
        </div>
  
      <% end %>
    </div>
  </div>

app/views/admin/projects/_form.html.erb
<%= form_for(([:admin, @project]), html: {'data-turbo' => "false"}) do |form| %>
  <%= render 'admin/shared/error', model: project %>

  <div class="form-group">
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name, class: "form-control form-control-lg" %>
  </div>

  <div class="form-group">
    <%= form.label :description, style: "display: block" %>
    <%= form.text_area :description, class: "form-control form-control-lg" %>
  </div>

  <div class="form-group">
    <%= form.submit class: "btn btn-primary btn-lg" %>
    <%= link_to "Back to projects", admin_projects_path, class: "btn btn-danger btn-lg" %>
  </div>
<% end %>

app/views/admin/projects/_project.html.erb
<div id="<%= dom_id project %>">
  <p>
    <strong>Name:</strong>
    <%= project.name %>
  </p>

  <p>
    <strong>Description:</strong>
    <%= project.description %>
  </p>

</div>

app/views/admin/projects/edit.html.erb
<div class="col-lg-12">
  
  <h1>Editing project</h1>

  <%= render "form", project: @project %>

</div>

app/views/admin/projects/index.html.erb
<div class="col-lg-12">
  <div class="form-group" style="display: flex; align-items: center;">
    <p style="color: green"><%= notice %></p>
    <h1>Projects</h1>
  </div>
  <div class="form-group" style="margin-bottom: 100px;">
    <%= link_to "New project", new_admin_project_path, class: "btn btn-primary btn-lg", style: "float: right;" %>
  </div>
  <div class="row">
    <div class="col-2">
        <%= render 'admin/projects/filter' %>
    </div>
    <div class="col-10">
      <table class="table table-bordered table-hover">
          <thead class="thead-dark">
              <tr>
                  <th class="text-center"><%= sort_link(@q, :name, default_order: :asc) %></th>
                  <th class="text-center">Description</th> 
                  <th colspan="3" class="text-center">Actions</th>
              </tr>
          </thead>
          <tbody class="tbody-light">
              <% @projects.each do |project| %>
                  <tr>
                      <td><%= project.name %></td>
                      <td><%= project.description %></td>
                      <td class="text-center"><%= link_to "View", admin_project_path(project), class: "btn btn-primary btn-sm" %></td>
                      <td class="text-center"><%= link_to "Edit", edit_admin_project_path(project), class: "btn btn-warning btn-sm" %></td>
                      <td class="text-center"><%= link_to 'Delete',admin_project_path(project),data: {turbo_method: :delete, turbo_confirm: 'Are you sure?'}, class: "btn btn-danger btn-sm" %></td>
                  </tr>
              <% end %>
          </tbody>
      </table>
    </div>  
    
    </div>
    <div style="margin: 0 auto; width: 18%;"><%== pagy_bootstrap_nav(@pagy) %></div>
</div>

app/views/admin/projects/new.html.erb
<div class="col-lg-12">

  <h1>New project</h1>

  <%= render "form", project: @project %>

</div>

app/views/admin/projects/show.html.erb
<div class="col-lg-12">
  <div class="card rounded-0 shadow mt-5 mb-5">
    <div class="card-body">
      <p style="color: green"><%= notice %></p>

      <%= render @project %>

      <div class="form-group">
        <%= link_to "Back to projects", admin_projects_path, class: "btn btn-danger btn-lg" %> | <%= link_to "Edit this project", edit_admin_project_path(@project), class: "btn btn-primary btn-lg" %>
      </div>
    </div>
  </div>
</div>